/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResultRouteImport } from './routes/result'
import { Route as StartRouteImport } from './routes/start'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiCareerRouteImport } from './routes/api/career'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiReadDocRouteImport } from './routes/api/read-doc'
import { Route as ApiRewriteRouteImport } from './routes/api/rewrite'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsSavedRouteImport } from './routes/jobs.saved'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareerRoute = ApiCareerRouteImport.update({
  id: '/api/career',
  path: '/api/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadDocRoute = ApiReadDocRouteImport.update({
  id: '/api/read-doc',
  path: '/api/read-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewriteRoute = ApiRewriteRouteImport.update({
  id: '/api/rewrite',
  path: '/api/rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSavedRoute = JobsSavedRouteImport.update({
  id: '/jobs/saved',
  path: '/jobs/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/career': typeof ApiCareerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/read-doc': typeof ApiReadDocRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/saved': typeof JobsSavedRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/career': typeof ApiCareerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/read-doc': typeof ApiReadDocRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/saved': typeof JobsSavedRoute
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/career': typeof ApiCareerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/read-doc': typeof ApiReadDocRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/saved': typeof JobsSavedRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/ats'
    | '/auth'
    | '/build'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/reset-password'
    | '/result'
    | '/start'
    | '/templates'
    | '/api/analyze'
    | '/api/career'
    | '/api/chat'
    | '/api/extract'
    | '/api/jobs'
    | '/api/read-doc'
    | '/api/rewrite'
    | '/companies/$companyId'
    | '/jobs/$jobId'
    | '/jobs/saved'
    | '/companies/'
    | '/jobs/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/ats'
    | '/auth'
    | '/build'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/reset-password'
    | '/result'
    | '/start'
    | '/templates'
    | '/api/analyze'
    | '/api/career'
    | '/api/chat'
    | '/api/extract'
    | '/api/jobs'
    | '/api/read-doc'
    | '/api/rewrite'
    | '/companies/$companyId'
    | '/jobs/$jobId'
    | '/jobs/saved'
    | '/companies'
    | '/jobs'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/ats'
    | '/auth'
    | '/build'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/reset-password'
    | '/result'
    | '/start'
    | '/templates'
    | '/api/analyze'
    | '/api/career'
    | '/api/chat'
    | '/api/extract'
    | '/api/jobs'
    | '/api/read-doc'
    | '/api/rewrite'
    | '/companies/$companyId'
    | '/jobs/$jobId'
    | '/jobs/saved'
    | '/companies/'
    | '/jobs/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AtsRoute: typeof AtsRoute
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultRoute: typeof ResultRoute
  StartRoute: typeof StartRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiCareerRoute: typeof ApiCareerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiReadDocRoute: typeof ApiReadDocRoute
  ApiRewriteRoute: typeof ApiRewriteRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsSavedRoute: typeof JobsSavedRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/career': {
      id: '/api/career'
      path: '/api/career'
      fullPath: '/api/career'
      preLoaderRoute: typeof ApiCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/read-doc': {
      id: '/api/read-doc'
      path: '/api/read-doc'
      fullPath: '/api/read-doc'
      preLoaderRoute: typeof ApiReadDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite': {
      id: '/api/rewrite'
      path: '/api/rewrite'
      fullPath: '/api/rewrite'
      preLoaderRoute: typeof ApiRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/saved': {
      id: '/jobs/saved'
      path: '/jobs/saved'
      fullPath: '/jobs/saved'
      preLoaderRoute: typeof JobsSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AtsRoute: AtsRoute,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultRoute: ResultRoute,
  StartRoute: StartRoute,
  TemplatesRoute: TemplatesRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiCareerRoute: ApiCareerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiReadDocRoute: ApiReadDocRoute,
  ApiRewriteRoute: ApiRewriteRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsSavedRoute: JobsSavedRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
